### ISSUE TITLE
Hamburger menu appears initially and disappears - island to grey background - win build 1809

### ISSUE THREAD

**Issue by mediabuff** [microsoft/Windows-appsample-Xaml-Hosting#4]
OS Build 18282.1000

Similar issue with following sample as well - grey area in the island.
https://github.com/clarkezone/cppwinrt/tree/master/Desktop/XamlIslandsWin32

**Comment by bmitchell287** [comment]
@mediabuff -Thanks for raising this, we're looking into it.

**Comment by bmitchell287** [comment]
@mediabuff - Thanks for the feedback. We couldn't reproduce on our side, but we've let the feature team know that this may be an issue on your specific Insider OS build and asked them to look into it.
