### ISSUE TITLE
Controls not appearing with Windows Insider 

### ISSUE THREAD

**Issue by bruce-armstrong** [microsoft/Windows-appsample-Xaml-Hosting#5]
I created a HyperV VM with Windows Insider 18290, Windows Insider SDK 18298 and Visual Studio 2017 Community Edition.  When running the code on that none of the controls display, just the text that indicate what the controls are.  What am I doing wrong?

![50387227-6929cf00-06ac-11e9-824e-7244cb5bcda2](https://user-images.githubusercontent.com/6356830/50608687-35a42d00-0e82-11e9-88c1-5abb24b82882.PNG)

**Comment by marb2000** [comment]
This sample is tested only in 1809 build. There is no warranty that the sample works on the insider builds given we are still in development. However, I tested on the #18305 build, and the controls render, but there is an issue with the transparencies. As a workaround, the transparency effects should be disabled in the OS Settings meanwhile we are finishing the work.

**Comment by bruce-armstrong** [comment]
I"m confused.  The readme file gives the list of requirements and indicates that insider builds are one of them:

Visual Studio 2017
C++ /WinRT Visual Studio Extension (VSIX)
Windows SDK Insider Preview Build 17763
**Windows 10 Insider Preview Build 17763**

**Comment by bruce-armstrong** [comment]
Confirmed working for me on Build 1089.  I'd just suggest updating the readme file.

**Comment by marb2000** [comment]
Thanks for your feedback. I have created a PR to update the Readme. I would love to listen more about your scenario so we can assist you. You can contact us at: XamlIslandsFeedback@microsoft.com
