### ISSUE TITLE
Crash when exiting app with debugger attached.

### ISSUE THREAD

**Issue by johanlindfors** [microsoft/Windows-appsample-Xaml-Hosting#9]
When running this sample with VS2017 or VS2019 debugger attached, I am experiencing a crash when exiting the app, as long  as I have interacted with any of the UWP controls attached to the sample. We need guidance on how to properly clean up and shutdown when using XAML Islands.

**Comment by stevewhims** [comment]
Hi, @johanlindfors, and apologies for not responding sooner. This sample is now obsolete. I'm about to remove the source code from this repo, and leave a redirection notice (to different samples) in the README. So I'll go ahead and close this issue now.

Thanks!
Steve
